--- 1. Users ---\nTRUNCATE TABLE users;\nINSERT INTO users (openId, name, email, loginMethod, role, createdAt, updatedAt, lastSignedIn) VALUES\n('nMq3brCZmFj5E3vGxhgU', 'Admin User', 'admin@bitsa.com', 'oauth', 'admin', '2025-11-17 15:17:23', '2025-11-17 15:17:23', '2025-11-17 15:17:23'),\n('iTmb97RjmqOtswOCHz6m', 'Regular User', 'user@bitsa.com', 'oauth', 'user', '2025-11-17 15:17:23', '2025-11-17 15:17:23', '2025-11-17 15:17:23');\n\n--- 2. Blog Posts ---\nTRUNCATE TABLE blog_posts;\nINSERT INTO blog_posts (title, slug, content, excerpt, category, authorId, featured, published, createdAt, updatedAt) VALUES\n('Defero rem desipio suffragium concido.', '-OkhJ2', 'Aeger quas carus distinctio amita ater utilis vulnus caste. Suffoco demoror aperiam deprecator libero demens cultura vesco acies spes. Tener supplanto sed patria maxime comprehendo coruscus.
Iure trans tamdiu laborum eius vitae delectus cogito impedit coepi. Recusandae cultellus cruciamentum. Demoror varietas cursim.
Amissio corrigo curo incidunt doloremque teres urbanus arbitro amet. Arguo allatus absorbeo bellicus abundans pel audax. Somniculosus via spoliatio ipsam vito coniecto tempus.
Voco contra bis caste crur ocer. At terebro accendo vesco capillus utilis illo via iure. Valeo canis strues audeo vulgaris clarus cumque.
Corona tolero consequatur vaco delectatio curvo decor articulus taedium. Summopere tabernus deleo alter solutio caput candidus usque. Illum cruciamentum demulceo assumenda doloremque arbitro quod utique decipio.', 'Maiores derelinquo terror. Amplexus absque solutio tondeo accedo trans crepusculum.', 'tutorial', '1', '1', '1', '2025-11-16 15:34:12', '2025-11-17 04:39:47'),\n('Sperno validus verto arca tenax.', '-uLEFF', 'Certe cum assentator tot caelum trepide temporibus socius adopto. Cursim aperiam aro color compello. Degusto culpa deinde verto vesco vir.
Tego supellex quae crudelis alias vindico clam correptius. Cumque accedo venia impedit umquam certus libero conspergo clibanus crustulum. Cauda adiuvo defetiscor cerno ullus.
Perferendis vindico non curatio. Demum decretum surculus nisi crepusculum aliqua defungo accedo bene. Enim tenus synagoga viriliter cunae umquam explicabo.
Caveo volup degero tergeo libero crux delego una. Chirographum aspicio colo depono ventosus vomito adsum argentum molestiae. Turba venio aspernatur caecus.
Perferendis unde pecco cur censura absum aer aureus. Creta suasoria crinis utilis perferendis capillus triumphus adipiscor. Varius tersus repudiandae strues.', 'Speciosus demonstro cubicularis vociferor cresco vulariter. Torqueo demulceo defungo delectus vitiosus apparatus facilis vorax desipio conor.', 'announcement', '1', '1', '1', '2025-11-16 16:26:23', '2025-11-17 02:36:28'),\n('Adhaero expedita corrupti vir claudeo.', '-RuLYA', 'Tenuis tempore commodo nulla solum accusantium suasoria neque vallum. Substantia combibo molestiae cohibeo. Quas iusto amicitia amaritudo conor eos aliquid aperte.
Sto toties abscido thesaurus annus facere curis trucido titulus. Astrum creber stultus terra tutamen suscipio aperio tabella terminatio. Delicate caelestis stultus.
Vulpes cuius aiunt admoneo. Vito benevolentia molestias talus accendo tollo dedico tempore. Vinco triduana attollo commodi facere aperio vulariter abeo tubineus cribro.
Verbera arbustum bis aeger vulgivagus. Bestia benevolentia callide victoria audentia. Patior pel accedo tabula voco compello vulariter congregatio.
Patior quod pecco adamo statua combibo ad. Victus tredecim texo carcer. Audacia umbra creta vorago.', 'Aetas ustulo voluptas veritatis textilis pectus sursum cetera deporto consequuntur. Vicissitudo cetera tergiversatio vindico comburo cogo.', 'tutorial', '1', '1', '1', '2025-11-17 04:08:41', '2025-11-17 06:05:28');\n\n--- 3. Events ---\nTRUNCATE TABLE events;\nINSERT INTO events (title, description, date, location, category, registrationLink, published, createdAt, updatedAt) VALUES\n('decumbo saepe perspiciatis corona Competition', 'Admitto error veniam. Concedo dolorum tergeo tepidus. Tempora traho cruentus maiores totam.
Delego suadeo tepesco claustrum. Eius paens volutabrum. Thema debilito acies summisse damnatio acsi adamo.
Clam voluptates vulgo succurro arbitro verto. Succedo condico maiores varius perspiciatis cui compono sonitus aestas. Tribuo uter tepesco repudiandae.', '2026-11-12 03:25:39', '824 N Main Suite 289', 'meeting', 'https://shoddy-tentacle.net', '1', '2025-11-17 02:23:39', '2025-11-17 11:28:56'),\n('speculum eveniet speculum reprehenderit Competition', 'Desipio damno hic demens autus. Totus amor cura patrocinor eos libero barba speculum ullam vomer. Stultus ars torrens contigo comburo.
Antea tertius adduco curriculum. Spiculum thymum vox error aureus clarus. Absque aqua artificiose alveus supra.
Caste cito thymum. Delicate conor adipiscor. Confero laboriosam cura carmen custodia.', '2026-01-12 07:00:25', '540 Broad Lane Apt. 248', 'competition', 'https://inborn-paintwork.info', '1', '2025-11-17 08:32:33', '2025-11-17 04:37:36');\n\n--- 4. Contact Submissions ---\nTRUNCATE TABLE contact_submissions;\nINSERT INTO contact_submissions (name, email, phone, subject, message, read, createdAt) VALUES\n('Bessie D''Amore', 'Dorian66@hotmail.com', '(885) 911-0839 x801', 'Nesciunt abduco taedium utique velit.', 'Bellicus volo thema. Vilicus suspendo curto creptio placeat cetera coadunatio cur ex. Dolores defleo attero sono thymbra. Fugit laboriosam temeritas aggero.', '0', '2025-11-16 16:58:27'),\n('Emilio Heller', 'Renee50@hotmail.com', '615.777.6853 x47288', 'Statim sponte approbo cohaero spoliatio.', 'Constans acervus corporis triduana quis. Curia ocer velociter beatus. Sub vinitor cibus valens spoliatio. Voluptates succedo credo tribuo audeo quasi cruciamentum.', '1', '2025-11-17 02:00:42');\n\n--- 5. Gallery Images ---\nTRUNCATE TABLE gallery_images;\nINSERT INTO gallery_images (title, description, imageUrl, category, displayOrder, published, createdAt, updatedAt) VALUES\n('adsidue defero ratione', 'Vivo voveo thesaurus inflammatio sunt tendo ustulo nostrum velut numquam.', 'https://loremflickr.com/800/600/tech?lock=8074671941013591', 'hardware', '7', '1', '2025-11-17 00:28:41', '2025-11-16 21:41:49'),\n('acidus spectaculum vomica', 'Voluntarius sapiente aestas dolore umquam solutio cognatus denego tepesco reprehenderit.', 'https://loremflickr.com/800/600/tech?lock=4569184911946678', 'team', '7', '1', '2025-11-16 19:06:17', '2025-11-16 15:32:13'),\n('arceo amaritudo depono', 'Commodi nesciunt vito ullam avaritia arbustum deleo nostrum amicitia pectus.', 'https://loremflickr.com/800/600/tech?lock=5638041237647782', 'hardware', '3', '1', '2025-11-16 18:19:26', '2025-11-17 09:25:07');\n